In [1]:
import pandas as pd
from sklearn import preprocessing

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
features = ([
    [-500.5],
    [-100.1],
    [0],
    [100.1],
    [900.9]])

In [4]:
ms = preprocessing.MinMaxScaler(feature_range=(0,1))

In [5]:
sf = ms.fit_transform(features)

In [6]:
sf

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [7]:
import numpy as np

In [8]:
x = np.array([
    [-1000.1],
    [-200.2],
    [500.5],
    [600.6],
    [9000.9]])

In [9]:
scaler = preprocessing.StandardScaler()

In [10]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
standardized = scaler.fit_transform(x)

In [12]:
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [13]:
print("平均:",round(standardized.mean()))
print('標準偏差:',standardized.std())

平均: 0.0
標準偏差: 1.0


In [14]:
rs = preprocessing.RobustScaler()

In [15]:
rs.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [16]:
from sklearn.preprocessing import Normalizer

In [17]:
features = np.array([
    [0.5,0.5],
    [1.1,3.4],
    [1.5,20.2],
    [1.63,34.4],
    [10.9,3.3]])

In [18]:
normal = Normalizer(norm="l2")

In [19]:
normal.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [20]:
features_l2_norm = Normalizer(norm="l2").transform(features)

In [21]:
features_l2_norm

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [22]:
features_l1_norm = Normalizer(norm="l1").transform(features)

In [23]:
features_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [24]:
print('最初の観測値の値の総計:', features_l1_norm[0,0] + features_l1_norm[0,1])

最初の観測値の値の総計: 1.0


In [26]:
from sklearn.preprocessing import PolynomialFeatures

In [27]:
features = np.array([
    [2,3],
    [2,3],
    [2,3]])

In [28]:
pi = PolynomialFeatures(degree=2, include_bias=False)

In [29]:
pi.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [30]:
interaction = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)

In [31]:
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [32]:
from sklearn.preprocessing import FunctionTransformer

In [33]:
def add_ten(x):
    return x + 10

In [34]:
tt = FunctionTransformer(add_ten)

In [35]:
tt.transform(features)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


array([[12, 13],
       [12, 13],
       [12, 13]])

In [36]:
df = pd.DataFrame(features, columns=["Feature_1","Feature_2"])

In [37]:
df.apply(add_ten)

Feature_1  Feature_2
0         12         13
1         12         13
2         12         13

In [38]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

In [39]:
features, _ = make_blobs(n_samples=10, n_features=2, centers=1, random_state= 1)

In [40]:
features[0,0] = 10000
features[0,1] = 10000

In [41]:
od = EllipticEnvelope(contamination=.1)

In [42]:
od.fit(features)

EllipticEnvelope(assume_centered=False, contamination=0.1, random_state=None,
                 store_precision=True, support_fraction=None)

In [43]:
od.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [44]:
features = features[:,0]

In [45]:
def indices_of_outliers(x):
    q1, q3 = np.percentile(x, [25,75])
    iqr = q3 - q1
    lb = q1 - (iqr * 1.5)
    ub = q3 + (iqr * 1.5)
    return np.where((x > ub) | (x < lb))

In [46]:
indices_of_outliers(features)

(array([0]),)

In [47]:
houses = pd.DataFrame()

In [48]:
houses['Price'] = [534433,39233,293222,4322032]

In [49]:
houses['Bathrooms'] = [2, 3.5, 2, 116]

In [50]:
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

In [51]:
houses[houses['Bathrooms'] < 20]

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1   39233        3.5         2500
2  293222        2.0         1500

In [52]:
houses["Outlier"] = np.where(houses['Bathrooms'] < 20, 0, 1)

In [53]:
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1    39233        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [54]:
houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses["Square_Feet"]]

In [55]:
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1    39233        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

In [56]:
from sklearn.preprocessing import Binarizer

In [57]:
age = np.array([
    [6],
    [12],
    [20],
    [36],
    [65]])

In [58]:
b = Binarizer(18)

In [59]:
b

Binarizer(copy=True, threshold=18)

In [61]:
b.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [64]:
np.digitize(age, bins=[20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [65]:
np.digitize(age, bins=[20,30,64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])

In [66]:
np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [67]:
from sklearn.cluster import KMeans

In [68]:
features, _ = make_blobs(n_samples=50, n_features=2, centers=3, random_state= 1)

In [69]:
df = pd.DataFrame(features, columns=["feature_1", "feature_2"])

In [70]:
cluster = KMeans(3, random_state=0)

In [71]:
cluster.fit(features)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=0, tol=0.0001, verbose=0)

In [73]:
df["group"] = cluster.predict(features)

In [74]:
df.head(5)

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

In [75]:
features = np.array([
    [1.1, 11.1],
    [2.2, 22.2],
    [3.3, 33.3],
    [4.4, 44.4],
    [np.nan, 55]])

In [77]:
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

In [78]:
df = pd.DataFrame(features, columns=["feature_1","feature_2"])

In [79]:
df.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

In [84]:
from sklearn.preprocessing import StandardScaler
from 