In [1]:
from sklearn import datasets
from sklearn.feature_selection import VarianceThreshold

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
iris = datasets.load_iris()

In [3]:
features = iris.data
target = iris.data

In [4]:
threshold = VarianceThreshold(threshold=.5)

In [5]:
fhv = threshold.fit_transform(features)

In [6]:
fhv[0:3]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2]])

In [7]:
threshold.fit(features).variances_

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()
fs = scaler.fit_transform(features)

In [10]:
selector = VarianceThreshold()
selector.fit(fs).variances_

array([1., 1., 1., 1.])

In [11]:
features = [
    [0,1,0],
    [0,1,1],
    [0,1,0],
    [0,1,1],
    [1,0,0]]

In [12]:
thresholder = VarianceThreshold(threshold=(.75 * (1 - .75)))

In [13]:
thresholder.fit_transform(features)

array([[0],
       [1],
       [0],
       [1],
       [0]])

In [14]:
import pandas as pd
import numpy as np

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [15]:
features = np.array([
    [1,1,1],
    [2,2,0],
    [3,3,1],
    [4,4,0],
    [5,5,1],
    [6,6,0],
    [7,7,1],
    [8,7,0],
    [9,7,1]])

In [16]:
df = pd.DataFrame(features)

In [17]:
corr_matrix = df.corr().abs()

In [18]:
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(np.bool))

In [19]:
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

In [20]:
df.drop(df.columns[to_drop],axis=1).head(3)

0  2
0  1  1
1  2  0
2  3  1

In [21]:
df.corr()

0         1         2
0  1.000000  0.976103  0.000000
1  0.976103  1.000000 -0.034503
2  0.000000 -0.034503  1.000000

In [22]:
upper

0         1         2
0 NaN  0.976103  0.000000
1 NaN       NaN  0.034503
2 NaN       NaN       NaN

In [23]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif

In [24]:
from sklearn.datasets import load_iris

In [25]:
iris = load_iris()
features = iris.data
target = iris.target

In [26]:
features = features.astype(int)

In [27]:
chi2_selector = SelectKBest(chi2, k=2)

In [28]:
features_kbest = chi2_selector.fit_transform(features, target)

In [29]:
print('元の特徴量:',features.shape[1])
print('削減後の特徴量:',features_kbest.shape[1])

元の特徴量: 4
削減後の特徴量: 2


In [30]:
fvalue_selector = SelectKBest(f_classif, k=2)

In [31]:
features_kbest = fvalue_selector.fit_transform(features, target)

In [32]:
print('元の特徴量:',features.shape[1])
print('削減後の特徴量:',features_kbest.shape[1])

元の特徴量: 4
削減後の特徴量: 2


In [33]:
from sklearn.feature_selection import SelectPercentile

In [34]:
fvalue_selector = SelectPercentile(f_classif, percentile=75)

In [35]:
features_kbest = fvalue_selector.fit_transform(features, target)

In [36]:
print('元の特徴量:',features.shape[1])
print('削減後の特徴量:',features_kbest.shape[1])

元の特徴量: 4
削減後の特徴量: 3


In [50]:
import warnings
from sklearn.datasets import make_regression
from sklearn.feature_selection import RFECV
from sklearn import datasets, linear_model

In [51]:
warnings.filterwarnings(action="ignore",module="scipy",message="^internal gelsd")

In [52]:
features, target =  make_regression(n_samples=10000, n_features=100, n_informative=2,random_state=1)

In [53]:
ols = linear_model.LinearRegression()

In [54]:
rfecv = RFECV(estimator=ols, step=1, scoring="neg_mean_aquared_error")