## 行列演習の基礎

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [2]:
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [4]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [7]:
#転置
X.T

array([[1, 3],
       [2, 4]])

In [8]:
# linear algebra:線形代数
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
#行列積
XX_inv = np.dot(X,X_inv)
XX_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [11]:
X = np.array([
    [2,3,4],
    [1,2,3]
])

In [12]:
X

array([[2, 3, 4],
       [1, 2, 3]])

In [14]:
X.shape

(2, 3)

In [15]:
row,col = X.shape

In [16]:
row

2

In [17]:
col

3

In [19]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


In [20]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [21]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
y

array([[1],
       [5],
       [6],
       [8]])

In [24]:
XtX = np.dot(X.T,X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [26]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [28]:
Xty = np.dot(X.T,y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [29]:
w = np.dot(XtX_inv,Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

## Scikit-learn

In [30]:
import sklearn

In [31]:
from sklearn.linear_model import LinearRegression

In [36]:
model = LinearRegression(fit_intercept=False)

In [37]:
#パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [38]:
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [39]:
model.intercept_

0.0

In [40]:
model.score(X,y)

0.6923076923076923

In [41]:
x = np.array([[1,2,3]])

In [43]:
#予測値
y_pred = model.predict(x)
y_pred

array([[3.]])